# Generated by Django 3.2.4 on 2021-06-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название проекта')),
                ('count', models.SmallIntegerField(verbose_name='количество выполненых проектов')),
                ('image', models.ImageField(upload_to='images/projects/%Y/%m/')),
            ],
        ),
    ]
